### ISSUE TITLE
Request to join textAnalysis-Hub collaborators here!

### ISSUE THREAD

**Issue by ebeshero** [newtfire/textAnalysis-Hub#3]
Students of textAnalysis! Please respond here with your new GitHub account to ask to be added as a collaborator on this repo.

**Comment by amw6765** [comment]
Anthony Wlodarczyk Add me at @amw6765  !!

**Comment by natalyamyers** [comment]
Add me, @natalyamyers

**Comment by amayadwillis** [comment]
please add me @amayadwillis :)

**Comment by STF5123** [comment]
Sheridan Fassett. Please add me @STF5123

**Comment by arrowarchive** [comment]
Rachel G. Please add me @arrowarchive

**Comment by NickyV1234** [comment]
Hello im not sure if im allready a collaborator from last semester but if im not i would like to be

**Comment by am0eba-byte** [comment]
with a cherry on top add @am0eba-byte (whomst is Mia)

**Comment by nickwright11** [comment]
Yo!! Please add me @nickwright11

**Comment by austinmurry** [comment]
Please add me! @austinmurry

**Comment by JesseBeckwith1998** [comment]
I need to be added to this repo please. @jessebeckwith1998

**Comment by Tricky-Keys** [comment]
Please add me to the repo @Tricky-Keys  (Isaac)

**Comment by JoshSige** [comment]
add me @joshsige

**Comment by wdjacca** [comment]
@ebeshero please add me:) @wdjacca

**Comment by Beeplosion** [comment]
@ebeshero please add me @Beeplosion

**Comment by Joelpie** [comment]
Hello, add @Joelpie please and carrots

**Comment by Emily-Levi** [comment]
Add me, please

**Comment by ebeshero** [comment]
I believe I've now sent an invitation to each of you to join the newtfire organization on Github! Please check the emails you used to set up your GitHub accounts and accept my invitation!

**Comment by ericsandbloom** [comment]
add me

**Comment by ericsandbloom** [comment]
add me @ericsandbloom

**Comment by kmh6907** [comment]
Add me please! @kmh6907

**Comment by ebeshero** [comment]
If I have responded with a thumbs-up here, that means I've sent you an invitation to join the textAnalysis-Hub. You can complete the joining process by accepting my invitation in your email (the email that you used to set up your GitHub account).

**Comment by san5281** [comment]
hello I am here and remember ACP.

**Comment by dxh405** [comment]
Hello! dxh405 please add me!

**Comment by tomsheehy** [comment]
Hi! @ebeshero add me please! Thanks

**Comment by jacobmeyer186** [comment]
Hello! Please add me @jacobmeyer186

**Comment by ebeshero** [comment]
If I've sent you an invitation to the newtFire organization, you can also accept it just by visiting [https://github.com/newtfire](https://github.com/newtfire)
